project:
  type: website

website:
  title: "biol827_biological_statistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - module1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

