project:
  type: book
  output-dir: docs

book:
  title: "BIOL827: Biological Statistics"
  author: "UNK Biology"
  date: "20 January 2025"
  chapters:
      - index.qmd
      - module1.qmd
      - module2.qmd
      - module5.qmd
      - citations.qmd
      
bibliography: references.bib
csl: the-auk.csl

format:
  html:
    theme: flatly
  pdf:
    documentclass: scrreprt

editor: visual

