project:
  type: book
  output-dir: docs

book:
  title: "biol827_biological_statistics"
  author: "UNK Biology"
  date: "20 January 2025"
  chapters:
      - index.qmd
      - about.qmd
      - module1.qmd

format:
  html:
    theme: flatly
  pdf:
    documentclass: scrreprt

editor: visual

