---
title: "Module 7"
author: "University of Nebraska at Kearney Biology"
format: html
editor: visual
---

## Learning Objectives

This problem set will provide an opportunity to:

-   Calculate probabilities for a binomial distribution

-   Calculate probabilities for a Poisson distribution

-   Conduct and interpret the statistical result from a binomial test.

## Datasets

We will not need to import a dataset this week!

## Packages

You will need to install and activate the following packages in RStudio: • binom RStudio

Procedures:

1\. Watch Module 7 lectures and problem set tutorial video. Implementation of these procedures are briefly discussed in the lectures.

2\. Open a new R script. If necessary, clear the environment and plots panes from R’s memory by clicking the broom icon at the top of both of these panes and clear the console by clicking on Edit menu \> Clear Console.

3\. If you have not already done so, install and activate the package indicated above. Section A. \[Optional\] Calculate a binomial probability distribution This exercise will illustrate how the shape of the binomial probability distribution changes with a different number of trials and probability of success.

4\. Enter and run the code below for calculating a binomial probability distribution. • Probabilities associated with a binomial distribution depend on the number of trials and the probability of success in each trial. These are the 2 inputs under ‘# Set parameters’ in the code below. • Look at the contents of object x. It contains a single list of values from 0 to 100 sequentially by 1. Each represents a possible number of successes out of 100 trials. Module 7: Problem Set BIOL827 2 • Look the contents of object pr.x. It contains a single list of binomial probabilities. These are the probabilities associated with observing each possible number of successes out of 100 trials. • The plot will graph the probabilities on the y-axis for each value from 0 to 100 along the x-axis. • If copy-pasting the code directly from these instructions, you may get an error message due to an issue with quotation marks. If so, you will need to re-type all quotation marks once pasted into RStudio.

5\. To visualize where an observed number of successes falls on the binomial probability distribution, add a new line of code: abline(v=number.successes). For example, if we have a hypothetical study in which there were 32 successes observed out of 100 trials, we could add a line at 32 successes to the probability distribution to illustrate where that number of successes falls with the code abline(v=32). • abline will add a straight line to the graph at a specified position. • v= tells RStudio to add a vertical line. • After the equals sign (=) enter a value to indicate where along the x-axis the line should be placed. ###Binomial distribution \# Set parameters total=100 #Total number of trials pr.event=0.5 #Probability of success for each trial #Create object with sequence representing all possible number of successes given the total number of trials x \<- seq(0,total, by=1) x #View the contents of object ‘x’ \# Calculate probabilities for each value in x based on total number of trials and probability of success assuming a binomial distribution pr.x \<- dbinom(x, total, pr.event) pr.x #View the contents of object ‘pr.x’ #Plot binomial probabilities for each value in object ‘x’ plot(pr.x, type="n", xlab="Successes out of 100 trials", ylab="Expected frequency", main="Binomial Distribution with Pr\[Success\]=0.5", ylim=c(0,1.0)) lines(x,pr.x) abline(v=32) Module 7: Problem Set BIOL827 3

6\. Keeping the total number of trials the same (total=100), change the probability of success (pr.event) from 0.5 to some other probability of success of your choosing. • Recall that probabilities should always be between 0 and 1.0. • How does this distribution compare to the one generated above?

7\. Change pr.event back to 0.5. Change “total=” to a different number of your choosing. • How do distributions created so far compare to one another? Section B. \[Optional\] Calculate a Poisson probability distribution This exercise will illustrate how the Poisson probability distribution changes with mean number of successes.

8\. Enter and run the code below for calculating a Poisson probability distribution. • Probabilities associated with a Poisson distribution depend on the mean number of successes (usually a mean per unit space or time). This is the only input under ‘Set parameters’ in the code. • Note object pr.x contains a single list of Poisson probabilities for a mean of 10 success. There is one probability corresponding to each value in object x. • The graph shows the probability (y-axis) of each value of x (x-axis). • If copy-pasting the code directly from these instructions, you may get an error message due to an issue with quotation marks. If so, you will need to re-type all quotation marks once pasted into RStudio. ###Poisson distribution \# Set parameters mean=10 #mean number of successes #Create object with sequence representing all possible mutually exclusive outcomes x \<- seq(0,100, by=1) x #View the contents of object ‘x’ \# Calculate probabilities for each value in x based on total number of trials and probability of success assuming a binomial distribution pr.x \<- dpois(x, mean) pr.x #View the contents of object ‘pr.x’ #Plot Poisson distribution values for each value in object x. plot(x, pr.x, type="n", xlab="Successes out of 100 trials", ylab="Expected frequency", main="Poisson Distribution with mean successes = 10", ylim=c(0,.5)) lines(x, pr.x) Module 7: Problem Set BIOL827 4

9\. Change the mean number of successes (mean=) from 10 to some other value of your choosing and re-run the code. • How do plotted values compare to those from the previous step? Section C. Conduct a binomial test Conduct a binomial test using Problem 2 of Chapter 7 in Whitlock and Schluter (2nd and 3rd editions page 194).

10\. Enter and run the code below to conduct a binomial test using binom.test() • x= observed number of successes • n= total number of trials • p= the null proportion (p0). This is the proportion of successes expected under the null hypothesis. • alternative= the alternative hypothesis (“two.sided”, “less”, or “greater”) • conf.level= desired level of uncertainty for calculation of confidence intervals calculated using the exact method.

11\. To calculate 95% Confidence Intervals using the Agresti-Coull method (as discussed in Section 7.3 of the textbook) install and activate package ‘binom’ to use the binom.confint() function.

12\. Enter and run the code below to calculate 95% Confidence Intervals using the Agresti- Coull method with the binom.confint() function. It has the following arguments: • x= observed number of successes • n= total number of trials • conf.level= desired level of uncertainty for calculation of confidence intervals. • methods= “ac” will produce confidence intervals using the Agresti-Coull method. \### Bionmial test #Whitlock and Schluter (2015, 2020) Chapter 7, Practice Problem 2 #Conduct the binomial test binom.test(x=19, n=25, p=0.5, alternative= "two.sided", conf.level=0.95) #Calculate 95% confidence interval for the estimated proportion of success using the Agresti-Coull method (section 7.3 of the text) library(binom) #activate package ‘binom’ binom.confint(x=19, n=25, conf.level=0.95, methods="ac") #Function ‘binom.confint’ Module 7: Problem Set BIOL827 5 13. The output should be as shown in Figure 1. • Compare the size of the 95% Confidence intervals calculated using the different methods (binom.test exact method versus Agresti-Coull method). Section D. Calculate the odds of success

14\. By hand or using RStudio as a calculator, calculate the odds of success by dividing the number of successes by the number of failures. This tells us how many times more or less likely success is compared to failure where odds = 1 means success is equally likely as failure, odds \> 1 means success is more likely than failure, and odds \< 1 means success is less likely than failure. Figure 1. Output for the binomial test and 95% confidence intervals for the probability of success calculated using the Agresti-Coull method conducted on data from Whitlock and Schluter (2015, 2020) Chapter 7, Practice Problem 2. p-value 95% CI (exact method) 95% CI (A-C method) Observed probability of success Module 7: Problem Set BIOL827 6 Problem Set 7 Assignment Directions and Questions: • Address questions as indicated below, not all parts identified in the book may be required and some questions are included here but not in the book. • You may complete questions by hand or using RStudio unless directed otherwise. • For the possibility of partial credit, provide your calculations, R code, and/or R output as a file upload at the end of the assignment form. Problem 1 A recent review (Seidelman et al. 2023) found that up to an average of 3% of surgical patients will develop an infection in or near the incision. A study be Coello et al. (2005) found that of 67,410 surgical patients in the UK between 1997 and 2001, 2,832 of them developed a surgical site infection (SSI). Is this infection rate more or less than the average rate of SSIs reported by Seidelman et al. (2023)? 1. (1 point) How many successes would we expect for 67,410 trials and a 3% infection rate (i.e., what is 3% of 67,410)? Round your answer to the nearest whole number. 2. (2 points) Estimate the proportion of patients experiencing SSIs in the Coello et al. (2005) study and give a 95% confidence interval for the estimate based on the observed sample. Round your answers to the nearest 0.001. 3. (4 points) Conduct a binomial test of the null hypothesis that the true rate of SSIs in the Coello et al. (2005) study is 3%. You will be asked to provide the following in Canvas: o What is the p-value? Round to the nearest 0.0001; if the p-value rounds to 0.0000, enter “\<0.0001”. o Based on this p-value, do you reject the null hypothesis or fail to reject the null hypothesis? 4. (2 points) Write 1-2 complete sentences in which you draw a biological conclusion from the test of the statistical hypothesis that SSIs occur to 3% of surgical patients in the Coello et al. (2005) study. o Include descriptive statistics (i.e., mean and 95% confidence interval) from the observed sample to provide context. o Parenthetically include the number of successes, number of trials, and the binomial test p-value in support of your biological conclusion. o Examples of how a biological conclusion differs from a statistical conclusion. § Statistical conclusion: “Based on the binomial test, I failed to reject the null hypothesis.” § Biological conclusion that provides context and uses statistical results to support the conclusion: “Courted males died due to sexual cannibalism at a Module 7: Problem Set BIOL827 7 rate of 34% (LCL 12%, UCL 56%). This does not differ significantly from the hypothesized rate of 50% mortality (21/52, p=0.1234).” 5. (2 points) Conduct a binomial test of the null hypothesis that the true rate of SSIs is 3% if the result had been 28 infections out of 674 surgeries. o You will be asked to provide the probability of success, 95%LCL, and 95%UCL rounded to the nearest 0.001. o You will also be asked to provide the p-value rounded to the nearest 0.0001 and statistical conclusion (reject or fail to reject the null hypothesis) in Canvas. If the p- value rounds to 0.0000, enter “\<0.0001”. 6. (2 points) Did the statistical conclusions differ from the two binomial tests? Why or why not? 7. (BONUS, +1 point possible) Create a plot showing the binomial probability distribution for the test of 28 SSIs out of 674 surgeries (+0.5 pts possible) with a vertical line at the observed number of successes (+0.5 pts possible). o You will be asked to paste, insert, or upload an image of the plot. Submitting your work for the Module 7 Problem Set Assignment: The Module 7 Problem Set Assignment is set up using a Quiz format. I recommend compiling your responses to all aspects of this assignment before beginning to fill in the form. Complete the assignment as directed by entering your work into the Module 6 Problem Set Assignment quiz page in Canvas on or before the due date indicated on the assignment page. References Coello, R, Charlett, A, Wilson, J, Ward, V, Pearson, A, Borriello, P. 2005. Adverse impact of surgical site infections in English hospitals. Journal of Hospital Infection 60: 93-103. DOI: 10.1016/j.jhin.2004.10.019 Siedelman, JL, Mantyh, CR, Anderson, DJ. 2023. Surgical Site Infection Prevention: A Review. JAMA 329: 244-252. DOI: 10.1001/jama.2022.2407

## 
